### ISSUE TITLE
how do i use this?

### ISSUE THREAD

**Issue by IAmTheNerdNextDoor** [recroom2016/OpenRec#2]
it just opens and then closes. also does the 19th of march 2019 build work with this as well?

**Comment by JacobRR123** [comment]
For you to fix this issue you have to download .Net 3.0 then open it and it will work

**Comment by brenden384** [comment]
how do i fix the openrec it keeps on opening and closeing please help

**Comment by Mrvrman** [comment]
if the .net 3.0 didnt work make sure itsx64
